### ISSUE TITLE
ValueError bei python tools/convert_trasse.py <trassen.csv>

### ISSUE THREAD

**Issue by MVGFan8xx** [C1710/TrainCompany-tools#1]
Also ich habe das befolgt, wie es in der readme stand. Habe alles installiert. Habe dann die .csv von trassenfinder.de genommen und die da reingehauen und dann kam ein Error raus und ich bin ziemlich ratlos.

Hier is der Error:
![image](https://user-images.githubusercontent.com/67337116/178848875-7945a911-f84f-4dcc-b610-ab0fac488d9f.png)

**Comment by C1710** [comment]
Achso, inzwischen musst du dafür `import_trassenfinder.py` benutzen. Das ist noch das alte Tool, was ich vergessen habe, zu löschen...

**Comment by MVGFan8xx** [comment]
Okie

**Comment by C1710** [comment]
Ich habe mir jetzt in letzter Zeit wenig/keine Mühe gegeben, das auch für andere brauchbar zu machen 😬

Aber immerhin können dir die Tools mit `--help` besser sagen, was es so für Parameter usw. gibt.

**Comment by MVGFan8xx** [comment]
Naja, jetzt is diese Warnung da
![image](https://user-images.githubusercontent.com/67337116/178851683-5ee6e8d6-0708-4fbc-be23-8f5203fdebbb.png)

Soll das so sein?

**Comment by C1710** [comment]
Ja, das ist okay. Wenn es die Standorte von Haltestellen nicht aus den Betriebsstellendaten finden kann, sucht es die über die Google Maps API raus, wenn man einen entsprechenden API-Key angibt 😅

**Comment by MVGFan8xx** [comment]
Okay, danke! :)

**Comment by C1710** [comment]
Bzw., ich glaube, ich hab da einen Fehler drin, dass es das _immer_ versucht, abzurufen 🥴
