### ISSUE TITLE
Wie kriegt das Programm die LATD/LONTD Zahlen in TC Koordinaten?

### ISSUE THREAD

**Issue by MVGFan8xx** [C1710/TrainCompany-tools#14]
Gibt es da einen Umrechnungsfaktor und wie wird dieser benutzt um von den Echt-Koordinaten auf die TC Koordinate zu kommen?

**Comment by C1710** [comment]
Das ganze läuft über die `pyproj`/`PROJ`-Bibliothek. Einen einfachen Umrechnungsfaktor gibt es nicht mehr (seit der Europa-Karte)

**Comment by C1710** [comment]
Falls du nur Koordinaten brauchst, gibt es das `convert_coordinates.py`-Tool. Da gibst du einfach Latitude und Longitude ein (z.B. auch einfach als Copy/Paste aus Google Maps) und es spuckt dir x/y-Koordinaten aus.

**Comment by MVGFan8xx** [comment]
okie danke!
