### ISSUE TITLE
import_brouter.py macht murks

### ISSUE THREAD

**Issue by MVGFan8xx** [C1710/TrainCompany-tools#23]
![image](https://user-images.githubusercontent.com/67337116/184555907-caf67a89-6b41-47f0-be62-4702a5940248.png)

**Comment by MVGFan8xx** [comment]
Habs genau so gemacht, wie du es auf Twitter gesagt hast.

**Comment by C1710** [comment]
Komisch... Sieht ein bisschen nach kaputter Internet-Verbindung oder so aus 🤔

**Comment by MVGFan8xx** [comment]
Am Internet kanns glaub ich nich liegen. Ich krieg 91 MB/s download und 40 MB/s Upload

**Comment by C1710** [comment]
> Am Internet kanns glaub ich nich liegen. Ich krieg 91 MB/s download und 40 MB/s Upload

Hm.... kannst du es mal mit `-d` noch versuchen? Da zeigt es dir dann im Log die Adresse an, die es aufruft (`photon.komoot.io/reverse/...`).

Versuch mal, ob das im Browser funktioniert...

**Comment by C1710** [comment]
Wäre es ein Fehler im Programm, würde der Server ja einen Fehler werfen (etwa wegen fehlerhafter Argumente) oder einfach gar nichts ausspucken.

Ein Timeout deutet glaube ich halt eher auf Verbindungsprobleme zum Server/Service hin.

**Comment by MVGFan8xx** [comment]
> Ein Timeout deutet glaube ich halt eher auf Verbindungsprobleme zum Server/Service hin.

Ja kann sein. Ich hab die URL die mir der Debug geschickt hat im Browser aufgerufen und es ging perfekt ohne Probleme.

**Comment by C1710** [comment]
Hm. Dann sollte es ja eigentlich auch da funktionieren, weil es ja halt nichts anderes macht, als die URL aufzurufen 🤔

**Comment by MVGFan8xx** [comment]
Naja, er kriegt halt ein paar durch aber danach bricht es ab.

**Comment by C1710** [comment]
Könnte es vielleicht irgendwie an der Firewall liegen? 🤔

Ergibt für mich aber auch irgendwie keinen Sinn...

**Comment by MVGFan8xx** [comment]
Keine Ahnung wenn ich ehrlich bin.

**Comment by MVGFan8xx** [comment]
Ok nevermind, jetzt hat es geklappt

**Comment by C1710** [comment]
> Naja, er kriegt halt ein paar durch aber danach bricht es ab.

Also ich glaube, es gibt ein Rate Limit bei dem Dienst. Ich habe das allerdings glaub ich noch nicht erreicht.
Vielleicht liegt das aber auch schlicht daran, dass in letzter Zeit unsere Internetverbindung manchmal ein bisschen hakt oder so. Ich baue mal morgen den `RateLimiter` ein, der in solchen Fällen länger wartet....

**Comment by MVGFan8xx** [comment]
Es ist sehr komisch. Manchmal klappts, machmal nich

**Comment by C1710** [comment]
> Es ist sehr komisch. Manchmal klappts, machmal nich

Dann kann es eigentlich wirklich nur zwei Ursachen haben:
1. Die Verbindung ist instabil/unzuverlässig (unwahrscheinlich)
2. Der Rate Limiter schlägt manchmal zu

Auf der Website steht auch:
> You can use the API for your project, but please be fair - extensive usage will be throttled. We do not guarantee for the availability and usage might be subject of change in the future.

**Comment by C1710** [comment]
> > Es ist sehr komisch. Manchmal klappts, machmal nich
> 
> Dann kann es eigentlich wirklich nur zwei Ursachen haben:
> 1. Die Verbindung ist instabil/unzuverlässig (unwahrscheinlich)
> 2. Der Rate Limiter schlägt manchmal zu
> 
> Auf der Website steht auch:
> > You can use the API for your project, but please be fair - extensive usage will be throttled. We do not guarantee for the availability and usage might be subject of change in the future.
> 
> 

Andererseits ist es eigentlich auch dafür gedacht, dass es schon während des Tippens Ergebnisse liefert, was ja durchaus eine vergleichbare Menge bedeuten kann wie das hier.

**Comment by C1710** [comment]
Rate Limiter ist jetzt drin, Image wird gebaut.

Damit gibt es zwei Änderungen:
1. Zwischen zwei Reverse-Geocoding-Anfragen wartet es immer eine halbe Sekunde
2. Tritt ein Fehler auf, wartet es 5 Sekunden und versucht es bis zu 3 Mal.

Also es wird jetzt deutlich länger dauern, sollte aber hoffentlich keine Timeout-Probleme mehr bereiten.

**Comment by C1710** [comment]
Funktioniert inzwischen alles?

**Comment by MVGFan8xx** [comment]
Ja mittlerweile funkt alles. Danke!
