### ISSUE TITLE
module 'statistics' has no attribute 'median_high'

### ISSUE THREAD

**Issue by MVGFan8xx** [C1710/TrainCompany-tools#31]
Wenn ich z.B. eine Trassenfinder csv Importieren will, kriegt das ding ein Problem und zwar spuckt es folgende Fehlermeldung aus:
![image](https://user-images.githubusercontent.com/67337116/187033660-7bbc8d85-389e-4f9b-8f56-e823a9fd9e2a.png)

Und die CSV ist das hier:
![image](https://user-images.githubusercontent.com/67337116/187033676-c0c2382e-003f-4326-934d-e1f26ed03c40.png)

**Comment by C1710** [comment]
Das ist immerhin mal nur ein kleiner Fehler 😂

Update kommt gleich

**Comment by C1710** [comment]
Ist jetzt behoben 😅

**Comment by C1710** [comment]
Das Problem war, dass ich das `statistics`-Script erstellt habe (was einem bisher Stationszahl und Gesamtstreckenlänge ausgibt).
Nur blöderweise hatte ich nicht dran gedacht, dass es auch das Python Standard-`statistics`-Modul gibt.
Ich habe es dann umbenannt und nicht bedacht, dass PyCharm auch die Nutzung noch umbenennt 🫣
