### ISSUE TITLE
ZeroDivisionError: float division by zero when importing gpx

### ISSUE THREAD

**Issue by embix** [C1710/TrainCompany-tools#37]
Tried to import attached [gpx](https://github.com/C1710/TrainCompany-tools/files/9479787/Praha-Chomutov.zip) and got `ZeroDivisionError`. No station/route files were changed.

Versions used:

- TrainCompany-tools: ghcr.io/c1710/traincompany-tools:latest (e6d805e6eafa which apparently is ghcr.io/c1710/traincompany-tools:v0.2.12))
- TrainCompany-Data: 86ce66e15a78cdbc5c4de791761a2e46c6aaf0c5

Log:

```
traincompany@0143b2729432:/workspaces/TrainCompany-Data$ import_brouter.py Praha-Chomutov.gpx 
ERROR:root:No station found for location (lat=50.25376228775088, lon=13.572353124618532)
ERROR:root:Ignoring station
ERROR:root:No station found for location (lat=50.305447499765656, lon=13.590297102928163)
ERROR:root:Ignoring station
ERROR:root:No station found for location (lat=50.31829201203518, lon=13.597490787506105)
ERROR:root:Ignoring station
ERROR:root:No station found for location (lat=50.426653009143344, lon=13.424112796783449)
ERROR:root:Ignoring station
Traceback (most recent call last):
  File "/tools/import_brouter.py", line 87, in <module>
    path_json, station_json = import_gpx_into_tc(
  File "/tools/import_brouter.py", line 37, in import_gpx_into_tc
    stations, paths = importer.import_data(gpx)
  File "/tools/importers/brouter_new.py", line 99, in import_data
    return stops, [tc_path_from_gpx(start, segment, end, overpass_response=overpass_response)
  File "/tools/importers/brouter_new.py", line 99, in <listcomp>
    return stops, [tc_path_from_gpx(start, segment, end, overpass_response=overpass_response)
  File "/tools/importers/brouter_new.py", line 502, in tc_path_from_gpx
    sinuosity = round(length / direct_distance, ndigits=3)
ZeroDivisionError: float division by zero
```

**Comment by embix** [comment]
Offtopic: warum holst du submodule nicht via https rein? Das macht üblicherweise weniger Schmerzen:

```
$ git sobmodules
Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
Failed to clone 'GitVersion'. Retry scheduled
Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
Failed to clone 'GitVersion' a second time, aborting
fatal: Failed to recurse into submodule path 'data/ds100bot'
```

**Comment by C1710** [comment]
> Offtopic: warum holst du submodule nicht via https rein? Das macht üblicherweise weniger Schmerzen:
> 
> ```
> $ git sobmodules
> Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
> Failed to clone 'GitVersion'. Retry scheduled
> Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
> Failed to clone 'GitVersion' a second time, aborting
> fatal: Failed to recurse into submodule path 'data/ds100bot'
> ```

Ich glaube, ich habe das einfach ohne ein bestimmtes Protokoll eingetippt 🤔
Bzw. vielleicht war es auch mit HTTPS?

SSH hab ich für Git nicht eingerichtet.

**Comment by C1710** [comment]
> > Offtopic: warum holst du submodule nicht via https rein? Das macht üblicherweise weniger Schmerzen:
> > 
> > ```
> > $ git sobmodules
> > Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
> > git@github.com: Permission denied (publickey).
> > fatal: Could not read from remote repository.
> > 
> > Please make sure you have the correct access rights
> > and the repository exists.
> > fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
> > Failed to clone 'GitVersion'. Retry scheduled
> > Cloning into 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion'...
> > git@github.com: Permission denied (publickey).
> > fatal: Could not read from remote repository.
> > 
> > Please make sure you have the correct access rights
> > and the repository exists.
> > fatal: clone of 'git@github.com:baeuchle/gitversion.git' into submodule path 'C:/git/TrainCompany-Tools-/data/ds100bot/GitVersion' failed
> > Failed to clone 'GitVersion' a second time, aborting
> > fatal: Failed to recurse into submodule path 'data/ds100bot'
> > ```
> 
> Ich glaube, ich habe das einfach ohne ein bestimmtes Protokoll eingetippt 🤔
> Bzw. vielleicht war es auch mit HTTPS?
> 
> SSH hab ich für Git nicht eingerichtet.

Kann es vielleicht sein, dass die Submodules vom Submodule per default SSH verwenden?
(Auch wenn die Sub-Sub-Modules da eh nicht hierfür relevant sind :D)

**Comment by embix** [comment]
> Kann es vielleicht sein, dass die Submodules vom Submodule per default SSH verwenden?

Dann hat eher derjenige, den du als submodule eingebunden hast das andere repo per git: als submodul eingebunden.

**Comment by embix** [comment]
Ich hab mit submodulen bisher auch keine gute Erfahrungen gemacht, immer war irgendwas. Es wird einem nicht einfach gemacht, das richtige zu tun. Deswegen hab ich die bei meinen Projekten auch wieder rausgeschmissen.

**Comment by C1710** [comment]
> Ich hab mit submodulen bisher auch keine gute Erfahrungen gemacht, immer war irgendwas. Es wird einem nicht einfach gemacht, das richtige zu tun. Deswegen hab ich die bei meinen Projekten auch wieder rausgeschmissen.

Ich brauche aber die entsprechenden Date. Und da sind Submodules glaub ich die sauberste Lösung.
Nur ist Git halt insgesamt (zumindest aus meiner Sicht) eher so.... sagen wir, ein notwendiges/alternativloses Übel 😄

**Comment by embix** [comment]
Ich hol externen Kram sonst per package management ran. Ich bin jetzt kein Schlangenbeschwörer, aber unter python sind doch pip und prosody üblich. Kann natürlich sein, daß in deinem Fall keiner ein Paket bereitgestellt hat.

Ich weiß garnicht was du hast, git selber ist das beste seid geschnitten Brot. (Zumindest wenn man sonst mit cvs, svn und tfs arbeiten mußte).

**Comment by C1710** [comment]
> Ich hol externen Kram sonst per package management ran. Ich bin jetzt kein Schlangenbeschwörer, aber unter python sind doch pip und prosody üblich. Kann natürlich sein, daß in deinem Fall keiner ein Paket bereitgestellt hat.
> 
> Ich weiß garnicht was du hast, git selber ist das beste seid geschnitten Brot. (Zumindest wenn man sonst mit cvs, svn und tfs arbeiten mußte).

Nö, das sind Daten-Repositories 😅
Und wenn Git wirklich gut wäre, wären Submodules ja auch kein Problem :D (Womit ich nicht sagen will, dass es bessere Optionen gibt, und wenn es welche gibt, dann sind die wahrscheinlich so eine Nische, dass es nichts bringt)

**Comment by embix** [comment]
Plastic SCM geht in Richtung gamedev/asset support. Gehört inzwischen zu Unity. Die haben auch gmaster und semantic merge gemacht. Git-Brücke gibts auch.

**Comment by C1710** [comment]
Aber mal zurück zum eigentlichen Problem:
Ich glaube, hier irgendwo werden zwei (oder mehr) Wegpunkte auf dieselbe Station gemappt:
![Kartenausschnitt](https://user-images.githubusercontent.com/10349490/188217016-b0a567ca-b328-4c61-9ffa-84eec9889775.png)

Das führt dann wiederum, dass "zwei" Stationen eine Distanz von 0 haben und es somit zu dem Fehler kommt.
Ich habe halt bisher dafür keine Checks eingebaut, da ich immer davon ausgehe, bzw. ausgegangen bin, dass die Wegpunkte auch jeweils bei verschiedenen Stationen liegen und nicht wie hier mehrere in der Nähe von einer :D

**Comment by embix** [comment]
ich mach gerade pr fertig

**Comment by embix** [comment]
Daß der manchmal - obwohl direkter weg möglich wäre - nen umweg/rückweg macht, hatte ich bei brouter schon mal. Da ging aber der gpx import wenigstens und die Streckenlänge/Twisting hab ich dann per Hand korrigiert.

**Comment by embix** [comment]
> Ich glaube, hier irgendwo werden zwei (oder mehr) Wegpunkte auf dieselbe Station

Der Grund, warum ich da vor und hinter der Station die zusätzlichen Punkte hingesemmelt habe - aber nicht direkt auf dem Stationsviereck - ist, weil er mir sonst die U-Bahnroute genommen und dann wirds noch absurder. Kann man das dem brouter irgendwie abgewöhnen?

Daß ich da nacharbeiten muß, wußte ich ich - daß er klatscht hätte ich nicht gedacht.

![brouter1PNG](https://user-images.githubusercontent.com/233264/188220628-46a764aa-b2bd-4b85-9eda-44d48eca265a.PNG)

![brouter2](https://user-images.githubusercontent.com/233264/188220742-94e8787a-f8ce-4461-9419-605ce3a9d82c.PNG)

**Comment by C1710** [comment]
Mh, würde es helfen, wenn ich einen Filter hinzufüge, dass du dann so Hilfspunkte speziell benennst o.Ä.?

Ansonsten macht es das bei mir alles anstandslos mit:
![brouter-Kartenausschnitt](https://user-images.githubusercontent.com/10349490/188221518-8712ffd3-8785-4d20-98f1-d0b3c7032f96.png)

Vielleicht hängt das irgendwie zusammen, dass ich bikerouter.de nutze? (Sollte aber eigentlich genauso funktionieren)

**Comment by embix** [comment]
> Mh, würde es helfen, wenn ich einen Filter hinzufüge, dass du dann so Hilfspunkte speziell benennst o.Ä.?

Meinst du in brouter den Punkten Namen geben? Da wüßte ich nicht, wie das geht (oder ob das geht).

Oder meinst du, dein Script fragt dann im Zweifel nach?

> Vielleicht hängt das irgendwie zusammen, dass ich bikerouter.de nutze? (Sollte aber eigentlich genauso funktionieren)

Keine Ahnung - vor TrainCompany kannte ich brouter u.ä. nicht mal. Einzig OpenStreetMap und openrailwaymap hatte ich vorher schon benutzt.

**Comment by C1710** [comment]
> > Mh, würde es helfen, wenn ich einen Filter hinzufüge, dass du dann so Hilfspunkte speziell benennst o.Ä.?
> 
> Meinst du in brouter den Punkten Namen geben? Da wüßte ich nicht, wie das geht (oder ob das geht).
> 
> Oder meinst du, dein Script fragt dann im Zweifel nach?

In der GPX-Datei haben die Wegpunkte Namen, bzw. Typen. Ich glaub, online kann man da nichts festlegen, das müsstest du dann manuell in der Datei machen.

**Comment by embix** [comment]
Bei > 20 via wäre meine Lust im gpx rumzuwerkeln eher gering und die Chance, daß man sich +/- eine Zeile vertut ist auch da gegeben. Da stehen ja tatsächlich nur lat/lon/name/type drin - mit sprechenderen Ortsnamen in der Datei wäre das gerade noch handhabbar.

Einfacher wäre es vermutlich, sich die Koordinaten und Position im Pfad der Station, die er in brouter nicht ordentlich selektiert zu merken, für das gpx erstmal außlassen und dann später händisch reinfrickeln (oder weglassen).

**Comment by embix** [comment]
FYI: Einen der Hilfspunkte hatte er trotzdem auf die U-Bahnstation gemappt.
