### ISSUE TITLE
import_brouter: unexpected keyword argument 'point'

### ISSUE THREAD

**Issue by embix** [C1710/TrainCompany-tools#40]
import_brouter.py crashes when importing one of those "not working" files.

```
traincompany@0143b2729432:/workspaces/TrainCompany-Data$ import_brouter.py nossen-freiberg-holzhau-diezweite.gpx 
Traceback (most recent call last):
  File "/tools/import_brouter.py", line 87, in <module>
    path_json, station_json = import_gpx_into_tc(
  File "/tools/import_brouter.py", line 37, in import_gpx_into_tc
    stations, paths = importer.import_data(gpx)
  File "/tools/importers/brouter_new.py", line 86, in import_data
    waypoint_location_to_station_location = self.collect_waypoint_stations(gpx.waypoints, reverse)
  File "/tools/importers/brouter_new.py", line 315, in collect_waypoint_stations
    station = with_osm_platform_data(station)
  File "/tools/importers/brouter_new.py", line 402, in with_osm_platform_data
    return Station(**station_dict)
TypeError: __init__() got an unexpected keyword argument 'point'
```

At first I thought the reason was Nossen not being marked with the typical station square (thus maybe mapping to a different node type? I have no idea how that works under the hood yet - didn't care either as it worked well enough) but when using only the Nossen-Freiberg route import didn't complain. So the Freiberg-Holzhau part might be the actual problem. As I haven't used brouter import with a known station somewhere in the middle, I cannot rule that out as cause either.

- [not_working.zip](https://github.com/C1710/TrainCompany-tools/files/9499903/not_working.zip)
- [working.zip](https://github.com/C1710/TrainCompany-tools/files/9499899/working.zip)

**Comment by C1710** [comment]
Also ich kann direkt erklären, warum es jetzt erst ein Problem gibt: Das ist deine erste Station, zu der es auf OSM Bahnsteigdaten gibt 😅

Einen Moment...

**Comment by embix** [comment]
holzhau-freiberg.gpx hätte ich zur Not auch noch im Angebot - da failt er genauso, aber klar, wenn es an einer der Stationen da liegt.

**Comment by C1710** [comment]
Fixed with #41

**Comment by C1710** [comment]
Ach, das ist ein Fehler, den ich schon zig mal hatte.

Das Problem ist, dass die `properties` zwar im `__dict__` der Klasse mit drin sind, aber nachher nicht als Argument für die `__init__`-Funktion akzeptiert werden. Ich vergesse das einfach schnell, mit zu berücksichtigen, wenn ich eine neue `property` einfüge 😅

Dass das nur so selten ein Problem ist, liegt schlicht daran, dass es diese "Rekonstruktion" mit dem Dict nur dann macht, wenn es gerade neue Bahnsteigdaten hinzufügen muss :D

**Comment by embix** [comment]
> Fixed with https://github.com/C1710/TrainCompany-tools/pull/41

Läuft 👍

> Dass das nur so selten ein Problem ist, liegt schlicht daran, dass es diese "Rekonstruktion" mit dem Dict nur dann macht, wenn es gerade neue Bahnsteigdaten hinzufügen muss :D

ah
